---
title: "Winter chilling"
author: "Patrick Snelgar"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
library(lubridate)
library(magrittr)
library(scales)
library(tidyverse)
library(here)
library(kableExtra)

if(!dir.exists(here("output"))) {
	dir.create(here("output"))
}

source(here("code/plot-themes.R"))
```

```{r data_import, include=FALSE}

current_Year <- as.integer(format(Sys.Date(), "%Y"))
oldest_Year <- current_Year - 10
met_data <- NULL

met_data <-  
	read_csv(here("input/MetWatch_Export.csv"), 
			 na = c('-',NA)) %>%
	rename(StationID = 1, StartDate = 2,
		   StopDate = 3, TemperatureMean = 4, 
		   RelativeHumidityMean = 5, RainTotal = 6,
		   RadiationMean = 7, WindSpeedMean = 8) %>%
	mutate(StopDate = dmy_hm(StopDate),
		   StartDate = dmy_hm(StartDate),
		   Month = month(StopDate),
		   Year = year(StopDate), 
		   DayOfYear = yday(StopDate))

				

by_site <- 
	met_data %>%
	filter(Month > 4) %>%
	mutate(IsBelowSevenC = ifelse(TemperatureMean < 7 & !is.na(TemperatureMean), 1, 0)) %>%
	group_by(Year, StationID) %>%
	mutate(ChillingHoursCumulative = cumsum(IsBelowSevenC))

richardsonChillTable <- read.csv(here("input/RichardsonChillingTable.csv"))


# by_site %>% filter(`Station ID` == "KER") %>% tail() %>% select(StopDate, temperature, ChillingHoursCumulative)
# 
# by_site %>% filter(Year == 2019 & Month > 3) %>% select(StopDate, temperature, ChillingHoursCumulative)


# Check for missing days
met_data %>%
	group_by(StationID, Year) %>%
	summarise(days_missing = c(NA, diff(yday(StopDate))) - 1, date = StopDate) %>%
	filter(days_missing > 0 | days_missing < -1) %>%
	knitr::kable()

# Check for missing hours
# be aware of daylight savings! 0300 in 9/10th Month, always has the same stop and start date, down to the hour
met_data %>%
	group_by(StationID, Year) %>%
	summarise(d = c(NA, diff(hour(StopDate))), date = StopDate, start_date = StartDate) %>%
	filter(d != 1 & d != -23 & date != start_date) %>%
	arrange(date) %>%
	knitr::kable()

# Check for duplicates
met_data %>%
	group_by(StationID, Year) %>%
	summarise(d = c(NA, diff(hour(StopDate))), date = StopDate) %>%
	filter(d == 0) %>%
	knitr::kable()


```

```{r graphs_current}

# numeric tick points for x axis
# only interested in data from April - October
DayOfYear_ticks <- 
	by_site%>%
	filter(StationID == "TPK" & (Month > 4 & Month < 10)) %$%
	pretty(x = DayOfYear, n = 7)

# labels for x axis ticks
Month_ticks <- format(as.Date(DayOfYear_ticks, origin), "%b-%d")

by_site %>% 
	filter(StationID == "TPK" & (Month > 4 & Month < 10) & Year >= oldest_Year & !Year == 2017) %>%
		ggplot() +
			geom_line(aes(DayOfYear, ChillingHoursCumulative, colour = factor(Year), size = factor(Year))) + 
			scale_size_manual(values = c(rep(0.5, 9), 1)) + 
			scale_color_manual(values = c("red", "blue", "gold","darkcyan", "orange", "purple",
										  "forestgreen", "darkturquoise", "green",  "black")) + 
			ggtitle(paste("Cumulative chilling hours - Te Puke", current_Year)) +
			ylim(0,1000) + 
			scale_x_continuous(breaks = DayOfYear_ticks, labels = Month_ticks) + 
			theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
			labs(x = "Date", y = "Cumulative hours (<7°C)", colour = "Year", caption = "2017 is excluded due to sensor error") + 
			guides(size = FALSE) + 
			theme_bw()


ggsave(here(paste0("output/Winter chilling - Te Puke ", current_Year, ".png")), width = 12, height = 8)

by_site %>% 
	filter(StationID == "KER" & (Month > 4 & Month < 10) & Year >= oldest_Year) %>%
		ggplot() +
			geom_line(aes(DayOfYear, ChillingHoursCumulative, colour = factor(Year), size = factor(Year))) + 
			scale_size_manual(values = c(rep(0.5, 10), 1)) + 
			scale_color_manual(values = c("red", "blue", "gold","darkcyan", "orange", "purple",
										  "forestgreen", "darkturquoise", "green", "cornflowerblue", "black")) + 
			ggtitle(paste("Cumulative chilling hours - Kerikeri", current_Year)) +
			ylim(0,1000) + 
			scale_x_continuous(breaks = DayOfYear_ticks, labels = Month_ticks) + 
			theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
			labs(x = "Date", y = "Cumulative hours (<7°C)", colour = "Year") + 
			guides(size = FALSE) + 
			theme_bw()


ggsave(here(paste0("output/Winter chilling - Kerikeri ", current_Year, ".png")), width = 12, height = 8)


by_site %>% 
	filter(StationID == "RIR" & (Month > 4 & Month < 10) & Year >= oldest_Year) %>%
		ggplot() +
			geom_line(aes(DayOfYear, ChillingHoursCumulative, colour = factor(Year), size = factor(Year))) + 
			scale_size_manual(values = c(rep(0.5, 10), 1)) + 
			scale_color_manual(values = c("red", "blue", "gold","darkcyan", "orange", "purple",
										  "forestgreen", "darkturquoise", "green", "cornflowerblue", "black")) + 
			ggtitle(paste("Cumulative chilling hours - Riwaka", current_Year)) +
			ylim(0,1700) + 
			scale_x_continuous(breaks = DayOfYear_ticks, labels = Month_ticks) + 
			theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
			labs(x = "Date", y = "Cumulative hours (<7°C)", colour = "Year") + 
			guides(size = FALSE) + 
			theme_bw()


ggsave(here(paste0("output/Winter chilling - Riwaka ", current_Year, ".png")), width = 12, height = 8)

```


```{r chilling_2021}

DayOfYear_ticks <- 
	by_site %>%
		filter(StationID == "TPK" & (Month > 4 & Month < 10) & (Year >= 2011 & Year < 2021)) %$%
		pretty(x = DayOfYear, n = 7)

# labels for x axis ticks
Month_ticks <- format(as.Date(DayOfYear_ticks, origin), "%b-%d")

by_site %>% 
	filter(StationID == "TPK" & (Month > 4 & Month < 10) & Year >= 2011 & !Year == 2017) %>%
		ggplot() +
			geom_line(aes(DayOfYear, ChillingHoursCumulative, colour = factor(Year), size = factor(Year))) + 
			scale_size_manual(values = c(rep(0.5, 9), 1)) + 
			scale_color_manual(values = c("red", "blue", "gold","darkcyan", "orange", "purple",
										  "forestgreen", "darkturquoise", "green",  "black")) + 
			ggtitle("Cumulative chilling hours - Te Puke 2021") +
			ylim(0,1000) + 
			scale_x_continuous(breaks = DayOfYear_ticks, labels = Month_ticks) + 
			theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
			labs(x = "Date", y = "Cumulative hours (<7°C)", colour = "Year", caption = "2017 is excluded due to sensor error") + 
			guides(size = "none") + 
			theme_bw()


ggsave(here("output/Winter chilling - Te Puke 2021.png"), width = 12, height = 8)

by_site %>% 
	filter(StationID == "KER" & (Month > 4 & Month < 10) & Year >= 2011) %>%
		ggplot() +
			geom_line(aes(DayOfYear, ChillingHoursCumulative, colour = factor(Year), size = factor(Year))) + 
			scale_size_manual(values = c(rep(0.5, 10), 1)) + 
			scale_color_manual(values = c("red", "blue", "gold","darkcyan", "orange", "purple",
										  "forestgreen", "darkturquoise", "green", "cornflowerblue", "black")) + 
			ggtitle("Cumulative chilling hours - Kerikeri 2021") +
			ylim(0,1000) + 
			scale_x_continuous(breaks = DayOfYear_ticks, labels = Month_ticks) + 
			theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
			labs(x = "Date", y = "Cumulative hours (<7°C)", colour = "Year") + 
			guides(size = "none") + 
			theme_bw()


ggsave(here("output/Winter chilling - Kerikeri 2021.png"), width = 12, height = 8)


# and tables for chill by end of July for Vic
# 2020 & 2021, by station (KER, TPK)

by_site %>% 
	filter(StationID %in% c("TPK", "KER") & Year %in% c(2020, 2021) & Month == 7) %>% 
	group_by(StationID, Year) %>% 
	arrange(desc(StopDate)) %>% 
	select(StationID, Year, ChillingHoursCumulative) %>% 
	slice(1) %>% 
	kable() %>% 
	kable_styling("striped")

```

```{r chilling_2018, include=FALSE}

DayOfYear_ticks <- 
	by_site %>%
		filter(StationID == "TPK" & (Month > 4 & Month < 10) & (Year >= 2008 & Year < 2019)) %$%
		pretty(x = DayOfYear, n = 7)

# labels for x axis ticks
Month_ticks <- format(as.Date(DayOfYear_ticks, origin), "%b-%d")

by_site %>% 
	filter(StationID == "TPK" & (Month > 4 & Month < 10) & (!Year == 2017 & (Year >= 2008 & Year < 2019))) %>%
		ggplot() +
			geom_line(aes(DayOfYear, ChillingHoursCumulative, colour = factor(Year), size = factor(Year))) + 
			scale_size_manual(values = c(rep(0.5, 9), 1)) + 
			scale_color_manual(values = c("red", "blue", "gold", "darkcyan", "orange", "purple",
										  "forestgreen", "darkturquoise", "green",  "black")) + 
			ggtitle("Cumulative chilling hours - Te Puke 2018") +
			ylim(0,2000) + 
			scale_x_continuous(breaks = DayOfYear_ticks, labels = Month_ticks) + 
			theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
			labs(x = "Date", y = "Cumulative hours (<7°C)", colour = "Year", caption = "2017 is excluded due to sensor error") + 
			guides(size = FALSE) + 
			theme_bw()

ggsave(here("output/Winter chilling - Te Puke 2018.png"), width = 12, height = 8)

by_site %>% 
	filter(StationID == "KER" & (Month > 4 & Month < 10) & (Year >= 2008 & Year < 2019)) %>%
		ggplot() +
			geom_line(aes(DayOfYear, ChillingHoursCumulative, colour = factor(Year), size = factor(Year))) + 
			scale_size_manual(values = c(rep(0.5, 10), 1)) + 
			scale_color_manual(values = c("red", "blue", "gold","darkcyan", "orange", "purple",
										  "forestgreen", "darkturquoise", "green", "cornflowerblue", "black")) + 
			ggtitle("Cumulative chilling hours - Kerikeri 2018") +
			ylim(0,1500) + 
			scale_x_continuous(breaks = DayOfYear_ticks, labels = Month_ticks) + 
			theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
			labs(x = "Date", y = "Cumulative hours (<7°C)", colour = "Year") + 
			guides(size = FALSE) + 
			theme_bw()

ggsave(here("output/Winter chilling - Kerikeri 2019.png"), width = 12, height = 8)


```

```{r budup_dates, echo = FALSE, include = FALSE}

# G11

early_g11 <- yday(ymd("2019/07/22"))
mid_g11 <- yday(ymd("2019/08/01"))
late_g11 <- yday(ymd("2019/08/07"))
vLate_g11 <- yday(ymd("2019/09/16"))

g11 <- data.frame(DayOfYear = c(early_g11, mid_g11, late_g11, vLate_g11))

# R19

early_r19 <- yday(ymd("2019/08/03"))
mid_r19 <- yday(ymd("2019/08/15"))
late_r19 <- yday(ymd("2019/08/21"))
vLate_r19 <- yday(ymd("2019/08/29"))

r19 <- data.frame(DayOfYear = c(early_r19, mid_r19, late_r19, vLate_r19))


by_site %>% 
	filter(`Station ID` == "TPK" & Year == 2019 & DayOfYear %in% c(g11$DayOfYear, r19$DayOfYear)) %>%
	group_by(DayOfYear) %>%
	summarise(temp_max = max(temperature),
			  temp_min = min(temperature),
			  rainfall = sum(`Rain Total`)) %>%
	mutate(date = as.Date(DayOfYear, origin = "2018/12/31"))
	

```

```{r richardsonGraphs, echo = FALSE}

by_site %>% 
	filter(StationID == "TPK" & (Month > 4 & Month < 10) & Year >= oldest_Year & !Year == 2017 & !is.na(TemperatureMean)) %>%
	mutate(richardsonUnit = richardsonChillTable$value[findInterval(TemperatureMean , richardsonChillTable$RangeMax[-7])+1],
		   richardsonChillingHours = cumsum(richardsonUnit)) %>%
		ggplot() +
			geom_line(aes(DayOfYear, richardsonChillingHours, colour = factor(Year), size = factor(Year))) + 
			scale_size_manual(values = c(rep(0.5, 9), 1)) + 
			scale_color_manual(values = c("red", "blue", "gold","darkcyan", "orange", "purple",
										  "forestgreen", "darkturquoise", "green",  "black")) + 
			ggtitle(paste("Cumulative Richardson chill units - Te Puke", current_Year)) +
			ylim(-300,1800) + 
			scale_x_continuous(breaks = DayOfYear_ticks, labels = Month_ticks) + 
			labs(x = "Date", y = "Richardson units", colour = "Year", caption = "2017 is excluded due to sensor error") + 
			guides(size = FALSE) +
			theme_bw() +
			theme(axis.text.x = element_text(angle = 45, hjust = 1))
			
		
ggsave(here(paste("output/Richardson Chilling hours - Te Puke", current_Year, ".png")), width = 12, height = 8)

by_site %>% 
	filter(StationID == "KER" & (Month > 4 & Month < 10) & Year >= oldest_Year & !is.na(TemperatureMean)) %>%
	mutate(richardsonUnit = richardsonChillTable$value[findInterval(TemperatureMean , richardsonChillTable$RangeMax[-7])+1],
		   richardsonChillingHours = cumsum(richardsonUnit)) %>%
		ggplot() +
			geom_line(aes(DayOfYear, richardsonChillingHours, colour = factor(Year), size = factor(Year))) + 
			scale_size_manual(values = c(rep(0.5, 10), 1)) + 
			scale_color_manual(values = c("red", "blue", "gold","darkcyan", "orange", "purple",
										  "forestgreen", "darkturquoise", "green", "cornflowerblue", "black")) + 
			ggtitle(paste("Cumulative Richardson chill units - Kerikeri", current_Year)) +
			ylim(-300,1800) + 
			scale_x_continuous(breaks = DayOfYear_ticks, labels = Month_ticks) + 
			labs(x = "Date", y = "Richardson units", colour = "Year") + 
			guides(size = FALSE) +
			theme_bw() +
			theme(axis.text.x = element_text(angle = 45, hjust = 1))
			
		
ggsave(here(paste("output/Richardson Chilling hours - Kerikeri", current_Year, ".png")), width = 12, height = 8)


by_site %>% 
	filter(StationID == "RIR" & (Month > 4 & Month < 10) & Year >= oldest_Year & !is.na(TemperatureMean)) %>%
	mutate(richardsonUnit = richardsonChillTable$value[findInterval(TemperatureMean , richardsonChillTable$RangeMax[-7])+1],
		   richardsonChillingHours = cumsum(richardsonUnit)) %>%
		ggplot() +
			geom_line(aes(DayOfYear, richardsonChillingHours, colour = factor(Year), size = factor(Year))) + 
			scale_size_manual(values = c(rep(0.5, 10), 1)) + 
			scale_color_manual(values = c("red", "blue", "gold","darkcyan", "orange", "purple",
										  "forestgreen", "darkturquoise", "green", "cornflowerblue", "black")) + 
			ggtitle(paste("Cumulative Richardson chill units - Riwaka", current_Year)) +
			ylim(-100,2200) + 
			scale_x_continuous(breaks = DayOfYear_ticks, labels = Month_ticks) + 
			labs(x = "Date", y = "Richardson units", colour = "Year") + 
			guides(size = FALSE) +
			theme_bw() +
			theme(axis.text.x = element_text(angle = 45, hjust = 1))
			
		
ggsave(here(paste("output/Richardson Chilling hours - Riwaka", current_Year, ".png")), width = 12, height = 8)

```

```{r, hc-alt-2020, include=FALSE}

DayOfYear_ticks <- 
	by_site%>%
	filter(StationID == "TPK" & (Month > 4 & Month < 10)) %$%
	pretty(x = DayOfYear, n = 7)

# labels for x axis ticks
Month_ticks <- format(as.Date(DayOfYear_ticks, origin), "%b-%d")

tpk_2020_graph <- 
	by_site %>% 
	filter(StationID == "TPK" & (Month > 4 & Month < 10) & Year > 2010 & !Year == 2017) %>%
		ggplot() +
			geom_line(aes(DayOfYear, ChillingHoursCumulative, colour = factor(Year), size = factor(Year))) + 
			scale_size_manual(values = c(rep(0.5, 8), 1)) + 
			scale_color_manual(values = c("red", "blue", "gold","darkcyan", "brown", "purple",
										  "forestgreen", "darkturquoise",  "black")) + 
			ggtitle("Cumulative chilling hours - Te Puke 2020") +
			scale_x_continuous(breaks = DayOfYear_ticks, labels = Month_ticks) + 
			scale_y_continuous(breaks = seq(0, 1000, 100), limits = c(0,1000),
							   expand = c(0,0)) +
			labs(x = "Date", y = "Cumulative hours (<7°C)", colour = "Year", caption = "2017 is excluded due to sensor error") + 
			guides(size = FALSE) + 
			publish_theme()


ggsave(here("output/Winter chilling (HC-alt) - Te Puke 2020.png"), tpk_2020_graph, width = 12, height = 8)

ker_2020_graph <- 
	by_site %>% 
	filter(StationID == "KER" & (Month > 4 & Month < 10) & Year > 2010) %>%
		ggplot() +
			geom_line(aes(DayOfYear, ChillingHoursCumulative, colour = factor(Year), size = factor(Year))) + 
			scale_size_manual(values = c(rep(0.5, 9), 1)) + 
			scale_color_manual(values = c("red", "blue", "gold","darkcyan", "brown", "purple",
										  "forestgreen", "darkturquoise", "hotpink",  "black")) + 
			ggtitle("Cumulative chilling hours - Kerikeri 2020") +
			scale_x_continuous(breaks = DayOfYear_ticks, labels = Month_ticks) + 
			scale_y_continuous(breaks = seq(0, 1000, 100), limits = c(0,1000),
							   expand = c(0,0)) +
			labs(x = "Date", y = "Cumulative hours (<7°C)", colour = "Year") + 
			guides(size = FALSE) + 
			publish_theme()


ggsave(here("output/Winter chilling (HC-alt) - Kerikeri 2020.png"), ker_2020_graph, width = 12, height = 8)

```

```{r rainfall}

# Select only june data
june_rainfall <- 
	met_data %>%
	filter(Month(StopDate) == 6) %>%
	group_by(StationID, Year(StopDate))
	
# How many 
june_rainfall %>%
	summarise(n = n() / 24)

june_rainfall %<>%
	filter(n() / 24 == 30 | Year(StopDate) == current_Year) %>%
	group_by(StationID, Year(StopDate)) %>%
	summarise(rainfall = sum(RainTotal, na.rm = TRUE)) %>%
	rename(Year = 2)

june_rainfall %>%
	filter(StationID == "TPK") %>%
	ggplot() +
		geom_bar(aes(factor(Year), rainfall, fill = rainfall), stat = "identity") +
		labs(x = "Year", y = "Total rainfall (mm)") +
		ggtitle("Historical June rainfall - Te Puke") +
		scale_y_continuous(limits = c(0,500)) +
		theme_bw()
		
ggsave(paste0("output/Historical June rainfall - Te Puke ", current_Year, ".png"), width = 12, height = 8)

```

```{r three-sites}
# Have to exclude 2017 data for TPK due to sensor error
historical <- 
	by_site %>%
	mutate(DayOfYear = yday(StopDate)) %>%
	filter(StationID %in% c("TPK", "KER", "RIR") 
		   & Year(StopDate) > current_Year - 5 
		   & !(StationID == "TPK" & Year(StopDate) == 2017) 
		   & DayOfYear >= 121 & DayOfYear <= 273
		   & Year(StopDate) != current_Year) %>%
	group_by(StationID, Year(StopDate)) %>%
	mutate(ChillingHoursCumulative = cumsum(IsBelowSevenC))

# any missing data?
historical %>%
	summarise(d = c(NA, diff(yday(StopDate))), date = StopDate) %>%
	filter(d > 1)

historical %>%
	ggplot() +
		geom_line(aes(StopDate, ChillingHoursCumulative, group = Year(StopDate))) +
		facet_wrap(~StationID)

five_Year_chill <- 
	historical %>%
	group_by(StationID, Year, DayOfYear) %>%
	arrange(DayOfYear) %>% 
	summarise(day_chill = max(ChillingHoursCumulative, na.rm = TRUE)) %>%
	group_by(StationID, DayOfYear) %>%
	summarise(historical_chill_hours = mean(day_chill))


# five_Year_chill %>%
# 	ggplot() +
# 		geom_line(aes(DayOfYear, chill_hours, colour = StationID)) + 
# 		scale_x_continuous(breaks = pretty_breaks(30))

historical_ticks <- 
	as.Date(seq(min(five_Year_chill$DayOfYear) - 1, max(five_Year_chill$DayOfYear), by = 7,), origin = "2021-01-01")

chill_colours <- brewer_pal("qual", 7, 1)(7)

by_site %>%
	filter(StationID %in% c("TPK", "KER", "RIR")
		   & Year == current_Year 
		   & DayOfYear >= 121 & DayOfYear <= 273) %>%
	ggplot() +
		geom_line(aes(DayOfYear, ChillingHoursCumulative, colour = StationID)) +
		geom_line(aes(DayOfYear, historical_chill_hours, colour = "5 Year mean"), data = five_Year_chill) + 
		facet_wrap(~StationID, labeller = labeller(StationID = c("KER" = "Kerikeri", "RIR" = "Riwaka", "TPK" = "Te Puke"))) + 
		scale_y_continuous(breaks = pretty_breaks(20)) +
		scale_x_continuous(breaks = yday(historical_ticks), labels = format(historical_ticks, "%b-%d")) +
		scale_colour_manual(values = c("5 Year mean" = "black", "TPK" = chill_colours[5], "KER" = chill_colours[2], "RIR" = chill_colours[4]), 
							labels = c("KER" = "Kerikeri", "RIR" = "Riwaka", "TPK" = "Te Puke")) +
		labs(colour = "Site", x = "Date", y = "Cumulative chilling hours (< 7°C)") +
		ggtitle(paste("Cumulative chilling hours -", current_Year)) +
		theme_bw() +
		theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))

ggsave(here("output/Three sites vs 5 Year mean - 2021.png"), width = 14, height = 8)


```

```{r Monthly}

block23_data <- 
	read_csv(here("input/Block23_MetStation.dat"), skip = 1)

met_data %>%
    filter(StationID == "TPK") %>%
    group_by(Year, Month) %>%
    summarise(avg_temp = mean(TemperatureMean, na.rm = TRUE)) %>%
    arrange(Month) %>%
    ggplot() +
        geom_point(aes(factor(Year), avg_temp, colour = avg_temp)) +
		scale_colour_gradient2(low = "blue", mid = "pink", high = "red", midpoint = 14) +
        facet_wrap(~Month, 
        		   scales = "free_x", 
        		   labeller = labeller(Month = c("1" = "January",
        		   								 "2" = "February",
        		   								 "3"  = "March", 
        		   								 "4" = "April",
        		   								 "5" = "May",
        										 "6" = "June", 
        										 "7" = "July", 
        										 "8" = "August", 
        										 "9" = "September", 
        										 "10" = "October", 
        										 "11" = "November", 
        										 "12" = "December"))) + 
		theme_bw() +
		theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))


block23_data %>%
	mutate(y = Year(TMSTAMP), m = Month(TMSTAMP)) %>%
	group_by(y, m) %>%
	summarise(avg_temp = mean(`AmbTemp_Avg`)) %>%
	ggplot() +
		geom_point(aes(factor(y), avg_temp, colour = avg_temp)) + 
		scale_colour_gradient2(low = "blue", mid = "pink", high = "red", midpoint = 14) +
        facet_wrap(~m, 
        		   scales = "free_x", 
        		   labeller = labeller(m = c("1" = "January",
        		   								 "2" = "February",
        		   								 "3"  = "March", 
        		   								 "4" = "April",
        		   								 "5" = "May",
        										 "6" = "June", 
        										 "7" = "July", 
        										 "8" = "August", 
        										 "9" = "September", 
        										 "10" = "October", 
        										 "11" = "November", 
        										 "12" = "December"))) + 
		theme_bw() +
		theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
```

```{r, include = FALSE}

# Annette found 7.2C is the correct cutoff of chilling to occur
# how does this stack up against 7C for Kerikeri

by_site %>% 
	filter(StationID == "KER" & Year == 2021) %>% 
	mutate(alt_hours = case_when(TemperatureMean <= 7.2 ~ 1, 
								 TemperatureMean > 7.2 ~ 0, 
								 is.na(TemperatureMean) ~ 0),
		   alt_cumulative = cumsum(alt_hours)) %>% 
	ggplot() +
		geom_line(aes(DayOfYear, ChillingHoursCumulative, colour = "7C")) +
		geom_line(aes(DayOfYear, alt_cumulative, colour = "7.2C")) +
		scale_colour_manual(values = c("7C" = "black", "7.2C" = "skyblue")) +
		scale_y_continuous(breaks = pretty_breaks(10), limits = c(0, 600)) +
		scale_x_continuous(breaks = pretty_breaks(20), limits = c(121, 275)) +
		theme_bw()


# How about Te Puke
by_site %>% 
	filter(StationID == "TPK" & Year == 2021) %>% 
	mutate(alt_hours = case_when(TemperatureMean <= 7.2 ~ 1, 
								 TemperatureMean > 7.2 ~ 0, 
								 is.na(TemperatureMean) ~ 0),
		   alt_cumulative = cumsum(alt_hours)) %>% 
	ggplot() +
		geom_line(aes(DayOfYear, ChillingHoursCumulative, colour = "7C")) +
		geom_line(aes(DayOfYear, alt_cumulative, colour = "7.2C")) +
		scale_colour_manual(values = c("7C" = "black", "7.2C" = "skyblue")) +
		scale_y_continuous(breaks = pretty_breaks(10), limits = c(0, 600)) +
		scale_x_continuous(breaks = pretty_breaks(20), limits = c(121, 275)) +
		theme_bw()


# Look for any missing values at the three sites for the current Year
by_site %>% 
	filter(Year == current_Year & is.na(TemperatureMean) & StationID %in% c("KER", "TPK", "RIW")) %>% 
	kable() %>% 
	kable_styling("striped")

# Only TPK has any (today = 2021-08-31)
na_data_tpk <- 
	by_site %>% 
	filter(Year == current_Year & is.na(TemperatureMean) & StationID == "TPK")

# find if there is matches in the raw file
# huh there isnt, wierd.
tpk_raw <- 
	read_csv(here("input/TPK.dat")) %>% 
	rename(ArrayID = 1, Year = 3, DayOfYear = 4, hm = 5, airtemp = 6) %>% 
	mutate(StopDate = as.Date(DayOfYear, origin = ymd(paste(Year - 1, "12-31", sep = "-"))),
		   StopDate = as_datetime(StopDate + hm/2400)) %>% 
	filter(ArrayID == 20 & Year == 2021)


# data table for TPK and KER with below 7C and Richardson units by Year
by_site %>% 
	filter(StationID %in% c("KER", "TPK") & (Month > 4 & Month < 10) & !is.na(TemperatureMean)) %>%  
	group_by(StationID, Year) %>% 
	mutate(richardsonUnit = richardsonChillTable$value[findInterval(TemperatureMean , richardsonChillTable$RangeMax[-7])+1],
		   richardsonChillingHours = cumsum(richardsonUnit)) %>% 
	slice(n()) %>% 
	select(StationID, Year, ChillingHoursCumulative, richardsonChillingHours) %>% 
	filter(Year == 2021)
	write_csv(here("output/Chilling hours table tpk ker.csv"))

```

