---
title: "Winter chilling"
author: "Patrick Snelgar"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE,
					  fig.width = 12)
library(lubridate)
library(magrittr)
library(scales)
library(tidyverse)
library(here)
library(kableExtra)

# clean up potential old or intermediary files
unlink(here("output"), recursive = TRUE)

if(!dir.exists(here("output"))) {
	dir.create(here("output"))
}

source(here("source/plot-themes.R"))

current_year <- as.integer(format(Sys.Date(), "%Y"))
oldest_year <- current_year - 10

```

```{r data_import}

met_data <- NULL

met_data <-  
	read_csv(here("input/MetWatch_Export.csv"), 
			 col_types = "cccddddd",
			 na = c('-',NA)) %>%
	rename(StationID = 1, StartDate = 2,
		   StopDate = 3, TemperatureMean = 4, 
		   RelativeHumidityMean = 5, RainTotal = 6,
		   RadiationMean = 7, WindSpeedMean = 8) %>%
	mutate(StopDate = dmy_hm(StopDate),
		   StartDate = dmy_hm(StartDate),
		   Month = month(StopDate),
		   Year = year(StopDate), 
		   DayOfYear = yday(StopDate)) %>% 
	group_by(StationID) %>% 
	arrange(StopDate)

				

by_site <- 
	met_data %>%
	filter(Month > 4) %>%
	mutate(IsBelowSevenC = ifelse(TemperatureMean < 7 & !is.na(TemperatureMean), 1, 0)) %>%
	group_by(Year, StationID) %>%
	mutate(ChillingHoursCumulative = cumsum(IsBelowSevenC))

richardsonChillTable <- read.csv(here("input/RichardsonChillingTable.csv"))


# Daily data - recorded at 0900 each morning and retrospectively dated.
daily_met_data <- 
	read_csv(here("input/MetWatch_Daily_Export.csv"), na = c("", NA, "-")) %>% 
	mutate(StartDate = dmy(StartDate),
		   Month = month(StartDate),
		   Year = year(StartDate), 
		   DayOfYear = yday(StartDate)) %>% 
	group_by(StationID) %>% 
	arrange(StartDate)

```

```{r data_check, eval=FALSE}
# Check for missing days
met_data %>%
	group_by(StationID, Year) %>%
	summarise(days_missing = c(NA, diff(yday(StopDate))) - 1, date = StopDate) %>%
	filter(days_missing > 0 | days_missing < -1) %>%
	kable(caption = "Missing days check") %>% 
	kable_styling('striped')

# Check for missing hours
# be aware of daylight savings! 0300 in 9/10th month, always has the same stop and start date, down to the hour
# removed duplicate values from this table as well, deal with that separately 
met_data %>%
	group_by(StationID, Year) %>%
	summarise(d = c(NA, diff(hour(StopDate))), date = StopDate, start_date = StartDate) %>%
	filter(d != 1 & d != -23 & date != start_date & d != 0) %>%
	arrange(date) %>%
	kable(caption = "Missing hours check") %>% 
	kable_styling('striped')

# Check for duplicates
met_data %>%
	group_by(StationID, Year) %>%
	summarise(d = c(NA, diff(hour(StopDate))), date = StopDate) %>%
	filter(d == 0) %>%
	kable(caption = "Duplicates check") %>% 
	kable_styling('striped')

# Do the same for the daily data set
daily_met_data %>% 
	group_by(StationID, Year) %>% 
	summarise(days_missing = c(NA, diff(yday(StartDate))) - 1, date = StartDate) %>% 
	filter(days_missing != 0) %>% 
	kable(caption = "missing days check") %>% 
	kable_styling("striped")

daily_met_data %>% 
	group_by(StationID, Year) %>% 
	summarise(duplicate = c(NA, diff(yday(StartDate))), date = StartDate) %>% 
	filter(duplicate == 0) %>% 
	kable(caption = "duplicate days check") %>% 
	kable_styling('striped')

```

```{r duplciate_removal, eval=FALSE}

# checks to see if there are duplicates using the same grouping method for filtering duplicates.

met_data %>% 
	group_by(StationID, StopDate) %>% 
	summarise(count = n()) %>% 
	filter(count > 1)


daily_met_data %>% 
	group_by(StationID, StartDate) %>% 
	summarise(count = n()) %>% 
	filter(count > 1)

# met_data %>% 
# 	group_by(StationID, StopDate) %>%
# 	slice(1)
# 
# daily_met_data %>% 
# 	group_by(StationID, StartDate) %>%
# 	slice(1)

```


```{r graphs}

# numeric tick points for x axis
# only interested in data from April - October
doy_ticks <- 
	by_site%>%
	filter(StationID == "TPK" & (Month > 4 & Month < 10)) %$%
	pretty(x = DayOfYear, n = 7)

# labels for x axis ticks
month_ticks <- format(as.Date(doy_ticks, origin), "%b-%d")

# colours are one value shorter for te puke with 2017 excluded,
# need to change this back once 2017 has lapsed to keep colours aligned between sites.
by_site %>% 
	filter(StationID == "TPK" & (Month > 4 & Month < 10) & Year >= oldest_year & !Year == 2017) %>%
		ggplot() +
			geom_line(aes(DayOfYear, ChillingHoursCumulative, colour = factor(Year), size = factor(Year))) + 
			scale_size_manual(values = c(rep(0.5, 9), 1)) + 
			scale_color_manual(values = c("red", "blue", "gold","darkcyan", "orange",
										  "forestgreen", "darkturquoise", "green", "cornflowerblue", "black")) + 
			ggtitle(paste("Cumulative chilling hours - Te Puke", current_year)) +
			scale_y_continuous(breaks = seq(0, 1000, 50), limits = c(0,1000)) + 
			scale_x_continuous(breaks = doy_ticks, labels = month_ticks) + 
			theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
			labs(x = "Date", y = "Cumulative hours (<7°C)", colour = "Year", caption = "2017 is excluded due to sensor error") + 
			guides(size = "none") + 
			theme_bw()


ggsave(here(paste0("output/Winter chilling - Te Puke ", current_year, ".png")), width = 12, height = 8)

by_site %>% 
	filter(StationID == "KER" & (Month > 4 & Month < 10) & Year >= oldest_year) %>%
		ggplot() +
			geom_line(aes(DayOfYear, ChillingHoursCumulative, colour = factor(Year), size = factor(Year))) + 
			scale_size_manual(values = c(rep(0.5, 10), 1)) + 
			scale_color_manual(values = c("red", "blue", "gold","darkcyan", "orange", "purple",
										  "forestgreen", "darkturquoise", "green", "cornflowerblue", "black")) + 
			ggtitle(paste("Cumulative chilling hours - Kerikeri", current_year)) +
			scale_y_continuous(breaks = seq(0, 1000, 50), limits = c(0,1000)) + 
			scale_x_continuous(breaks = doy_ticks, labels = month_ticks) + 
			theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
			labs(x = "Date", y = "Cumulative hours (<7°C)", colour = "Year") + 
			guides(size = "none") + 
			theme_bw()


ggsave(here(paste0("output/Winter chilling - Kerikeri ", current_year, ".png")), width = 12, height = 8)


by_site %>% 
	filter(StationID == "RIR" & (Month > 4 & Month < 10) & Year >= oldest_year) %>%
		ggplot() +
			geom_line(aes(DayOfYear, ChillingHoursCumulative, colour = factor(Year), size = factor(Year))) + 
			scale_size_manual(values = c(rep(0.5, 10), 1)) + 
			scale_color_manual(values = c("red", "blue", "gold","darkcyan", "orange", "purple",
										  "forestgreen", "darkturquoise", "green", "cornflowerblue", "black")) + 
			ggtitle(paste("Cumulative chilling hours - Riwaka", current_year)) +
			scale_y_continuous(breaks = seq(0, 1700, 100), limits = c(0,1700)) + 
			scale_x_continuous(breaks = doy_ticks, labels = month_ticks) + 
			theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
			labs(x = "Date", y = "Cumulative hours (<7°C)", colour = "Year") + 
			guides(size = "none") + 
			theme_bw()


ggsave(here(paste0("output/Winter chilling - Riwaka ", current_year, ".png")), width = 12, height = 8)

```

```{r richardsonGraphs, eval=FALSE}

by_site %>% 
	filter(StationID == "TPK" & (Month > 4 & Month < 10) & Year >= oldest_year & !Year == 2017 & !is.na(TemperatureMean)) %>%
	mutate(richardsonUnit = richardsonChillTable$value[findInterval(TemperatureMean , richardsonChillTable$RangeMax[-7])+1],
		   richardsonChillingHours = cumsum(richardsonUnit)) %>%
		ggplot() +
			geom_line(aes(DayOfYear, richardsonChillingHours, colour = factor(Year), size = factor(Year))) + 
			scale_size_manual(values = c(rep(0.5, 9), 1)) + 
			scale_color_manual(values = c("red", "blue", "gold","darkcyan", "orange", "purple",
										  "forestgreen", "darkturquoise", "green",  "black")) + 
			ggtitle(paste("Cumulative Richardson chill units - Te Puke", current_year)) +
			ylim(-300,1800) + 
			scale_x_continuous(breaks = doy_ticks, labels = month_ticks) + 
			labs(x = "Date", y = "Richardson units", colour = "Year", caption = "2017 is excluded due to sensor error") + 
			guides(size = "none") +
			theme_bw() +
			theme(axis.text.x = element_text(angle = 45, hjust = 1))
			
		
ggsave(here(paste("output/Richardson Chilling hours - Te Puke", current_year, ".png")), width = 12, height = 8)

by_site %>% 
	filter(StationID == "KER" & (Month > 4 & Month < 10) & Year >= oldest_year & !is.na(TemperatureMean)) %>%
	mutate(richardsonUnit = richardsonChillTable$value[findInterval(TemperatureMean , richardsonChillTable$RangeMax[-7])+1],
		   richardsonChillingHours = cumsum(richardsonUnit)) %>%
		ggplot() +
			geom_line(aes(DayOfYear, richardsonChillingHours, colour = factor(Year), size = factor(Year))) + 
			scale_size_manual(values = c(rep(0.5, 10), 1)) + 
			scale_color_manual(values = c("red", "blue", "gold","darkcyan", "orange", "purple",
										  "forestgreen", "darkturquoise", "green", "cornflowerblue", "black")) + 
			ggtitle(paste("Cumulative Richardson chill units - Kerikeri", current_year)) +
			ylim(-300,1800) + 
			scale_x_continuous(breaks = doy_ticks, labels = month_ticks) + 
			labs(x = "Date", y = "Richardson units", colour = "Year") + 
			guides(size = "none") +
			theme_bw() +
			theme(axis.text.x = element_text(angle = 45, hjust = 1))
			
		
ggsave(here(paste("output/Richardson Chilling hours - Kerikeri", current_year, ".png")), width = 12, height = 8)


by_site %>% 
	filter(StationID == "RIR" & (Month > 4 & Month < 10) & Year >= oldest_year & !is.na(TemperatureMean)) %>%
	mutate(richardsonUnit = richardsonChillTable$value[findInterval(TemperatureMean , richardsonChillTable$RangeMax[-7])+1],
		   richardsonChillingHours = cumsum(richardsonUnit)) %>%
		ggplot() +
			geom_line(aes(DayOfYear, richardsonChillingHours, colour = factor(Year), size = factor(Year))) + 
			scale_size_manual(values = c(rep(0.5, 10), 1)) + 
			scale_color_manual(values = c("red", "blue", "gold","darkcyan", "orange", "purple",
										  "forestgreen", "darkturquoise", "green", "cornflowerblue", "black")) + 
			ggtitle(paste("Cumulative Richardson chill units - Riwaka", current_year)) +
			ylim(-100,2200) + 
			scale_x_continuous(breaks = doy_ticks, labels = month_ticks) + 
			labs(x = "Date", y = "Richardson units", colour = "Year") + 
			guides(size = "none") +
			theme_bw() +
			theme(axis.text.x = element_text(angle = 45, hjust = 1))
			
		
ggsave(here(paste("output/Richardson Chilling hours - Riwaka", current_year, ".png")), width = 12, height = 8)

```

```{r rainfall}

# Select only june data
june_rainfall <- 
	met_data %>%
	filter(month(StopDate) == 6) %>%
	group_by(StationID, year(StopDate))

june_rainfall_summary <- 
	june_rainfall %>% 
	filter(n() / 24 == 30 | year(StopDate) == current_year) %>%
	group_by(StationID, year(StopDate)) %>%
	summarise(rainfall = sum(RainTotal, na.rm = TRUE)) %>%
	rename(year = 2)

n_years <- 
	june_rainfall_summary %>% 
	filter(StationID == "TPK") %$% 
	length(year)

june_rainfall_summary %>%
	filter(StationID == "TPK") %>%
	arrange(desc(year)) %>% 
	mutate(smaller_than = case_when(rainfall >= first(rainfall) & !(year == current_year) ~ 1, 
									year == current_year ~ 2,
									TRUE ~ 0)) %>% 
	ggplot() +
		geom_bar(aes(factor(year), rainfall, fill = factor(year)), stat = "identity") +
		labs(x = "Year", y = "Total rainfall (mm/month)", caption = "previous years are total monthly rainfall, current year is total rainfall to date.") +
		ggtitle("Historical June rainfall - Te Puke") +
		scale_y_continuous(limits = c(0,500)) +
		# scale_colour_manual(values = c("1" = alpha("black", 0.5), "0" = alpha("forestgreen", 0.5), "2" = alpha("blue", 0.5))) +
		#scale_fill_manual(breaks = c(2,1,0), values = c("1" = alpha("tomato", 0.8), "0" = alpha("forestgreen", 0.8), "2" = alpha("blue", 0.9)),
		#				  name = "", labels = c("0" = "Less than current", "1" = "More than current", "2" = "Current year")) +
		scale_fill_manual(breaks = 2003:2022, values = c(rep("lightgrey", 19), "blue")) +
		geom_text(aes(x = "2004", y = 205, label = "Average June rainfall")) +
		geom_hline(aes(yintercept = mean(rainfall)), alpha = 0.8) +
		guides(fill = "none") +
		theme_bw()
		
ggsave(here(paste0("output/Historical June rainfall - Te Puke ", current_year, ".png")), width = 12, height = 8)

```

### Five year average vs current years' chill

```{r three-sites}
# Have to exclude 2017 data for TPK due to sensor error
# 
historical <- 
	by_site %>%
	mutate(doy = yday(StopDate)) %>%
	filter(StationID %in% c("TPK", "KER", "RIR")
		   & year(StopDate) >= current_year - 5 
		   & !year(StopDate) == current_year 
		   & !(StationID == "TPK" & year(StopDate) == 2017) 
		   & doy >= 121 & doy <= 273 
		   & year(StopDate) != current_year) %>%
	group_by(StationID, year(StopDate)) %>%
	mutate(chilling_hours = cumsum(IsBelowSevenC))

# any missing data?
# historical %>%
# 	summarise(d = c(NA, diff(yday(StopDate))), date = StopDate) %>%
# 	filter(d > 1)
# 
# historical %>%
# 	ggplot() +
# 		geom_line(aes(StopDate, chilling_hours, group = year(StopDate))) +
# 		facet_wrap(~StationID)

five_year_chill <- 
	historical %>%
	group_by(StationID, Year, doy) %>%
	arrange(doy) %>% 
	summarise(day_chill = max(chilling_hours, na.rm = TRUE)) %>%
	group_by(StationID, doy) %>%
	summarise(historical_chill_hours = mean(day_chill))


# five_year_chill %>%
# 	ggplot() +
# 		geom_line(aes(doy, chill_hours, colour = StationID)) + 
# 		scale_x_continuous(breaks = pretty_breaks(30))

historical_ticks <- 
	as.Date(seq(min(five_year_chill$doy) - 1, max(five_year_chill$doy), by = 7,), origin = "2021-01-01")

chill_colours <- brewer_pal("qual", 7, 1)(7)

by_site %>%
	filter(StationID %in% c("TPK", "KER", "RIR")
		   & Year == current_year 
		   & DayOfYear >= 121 & DayOfYear <= 273) %>%
	ggplot() +
		geom_line(aes(DayOfYear, ChillingHoursCumulative, colour = StationID)) +
		geom_line(aes(doy, historical_chill_hours, colour = "5 year mean"), data = five_year_chill) + 
		facet_wrap(~StationID, labeller = labeller(StationID = c("KER" = "Kerikeri", "RIR" = "Riwaka", "TPK" = "Te Puke"))) + 
		scale_y_continuous(breaks = pretty_breaks(20)) +
		scale_x_continuous(breaks = yday(historical_ticks), labels = format(historical_ticks, "%b-%d")) +
		scale_colour_manual(values = c("5 year mean" = "black", "TPK" = chill_colours[5], "KER" = chill_colours[2], "RIR" = chill_colours[4]), 
							labels = c("KER" = "Kerikeri", "RIR" = "Riwaka", "TPK" = "Te Puke")) +
		labs(colour = "Site", x = "Date", y = "Cumulative chilling hours (< 7°C)") +
		ggtitle(paste("Cumulative chilling hours -", current_year)) +
		theme_bw() +
		theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))

ggsave(here(paste0("output/Three sites vs 5 year mean - ", current_year, ".png")), width = 16, height = 8)


```

### Seven day snapshot

```{r seven_day_snapshot}

# table the increase in chill hours 
current_year_chill <- 
	met_data %>% 
	filter(StationID %in% c("TPK", "KER", "RIR") & Year == current_year & Month %in% 5:9) %>% 
	group_by(StationID) %>% 
	mutate(below_seven = case_when(TemperatureMean < 7.0 ~ 1,
								   TRUE ~ 0),
		   cumulative_chill = cumsum(below_seven)) 


seven_day_snapshot <- 
	current_year_chill %>% 
	filter(StopDate >= (today() - 7)) %>% 
	summarise(diff_chill = last(cumulative_chill) - first(cumulative_chill),
			  current_chill = last(cumulative_chill),
			  average_temp = mean(TemperatureMean, na.rm = TRUE),
			  rainfall = sum(RainTotal, na.rm = TRUE))
	

seven_day_snapshot_table <- 
	seven_day_snapshot %>% 
	mutate(station_long_name = case_when(StationID == "TPK" ~ "Te Puke",
										 StationID == "KER" ~ "Kerikeri",
										 StationID == "RIR" ~ "Riwaka"),
		   station_long_name = factor(station_long_name, levels = c("Kerikeri", "Te Puke", "Riwaka"), ordered = TRUE)) %>% 
	select(station_long_name, current_chill, diff_chill, average_temp, rainfall) %>% 
	arrange(station_long_name) %>% 
	kable(caption = paste("Seven day snapshot", today()),
		  digits = 1,
		  format = "html",
		  col.names = c("Location", "Total chill hours", "Seven day chill hours", "Average temperature (°C)", "Total rainfall (mm)")) %>% 
	kable_styling('striped')

seven_day_snapshot_table

seven_day_snapshot_table %>%
	save_kable("../output/seven-day-snapshot.png", bs_theme = "cerulean")

```

### Monthly averge temperature

```{r monthly_temps}

# calculate the mean May, June & July temps for each site
# both historically and currently

# generate footnote for incomplete months
current_month <- month(today())
mjj_footnote <- ""

if(current_month <= 7) {
	mjj_footnote <- paste0("Data is incomplete for ", month.name[current_month], " ", current_year)
}

mjj_summary <- 
	daily_met_data %>% 
		filter(Month %in% c(5, 6, 7) & StationID %in% c("KER", "TPK", "RIR") & Year >= oldest_year) %>% 
		group_by(StationID, Year, Month) %>% 
		summarise(monthly_mean = mean(c(TemperatureMin, TemperatureMax), na.rm = TRUE)) %>% 
		mutate(month_name = case_when(Month == 5 ~ "May",
									  Month == 6 ~ "June",
									  Month == 7 ~ "July")) 

mjj_summary %>% 
	filter(StationID == "KER") %>% 
	mutate(month_name = factor(month_name, levels = c("May", "June", "July"))) %>% 
	ggplot() +
		geom_point(aes(Year, monthly_mean), size = 4) + 
		scale_x_continuous(breaks = oldest_year:current_year) +
		scale_y_continuous(breaks = 10:18, limits = c(10,18)) +
		labs(y = "Monthly mean temperature (°C)", x = "", caption = mjj_footnote) +
		facet_wrap(~month_name) + 
		ggtitle("Kerikeri - May, June & July average temperature") +
		theme_bw()

ggsave(here("output/Kerikeri - monthly average temperature.png"), width = 12, height = 8)
		
mjj_summary %>% 
	filter(StationID == "TPK") %>% 
	mutate(month_name = factor(month_name, levels = c("May", "June", "July"))) %>% 
	ggplot() +
		geom_point(aes(Year, monthly_mean), size = 4) + 
		scale_x_continuous(breaks = oldest_year:current_year) +
		scale_y_continuous(breaks = 8:15, limits = c(8,15)) +
		labs(y = "Monthly mean temperature (°C)", x = "", caption = mjj_footnote) +
		facet_wrap(~month_name) + 
		ggtitle("Te Puke - May, June & July average temperature") +
		theme_bw()

ggsave(here("output/Te Puke - monthly average temperature.png"), width = 12, height = 8)

mjj_summary %>% 
	filter(StationID == "RIR") %>% 
	mutate(month_name = factor(month_name, levels = c("May", "June", "July"))) %>% 
	ggplot() +
		geom_point(aes(Year, monthly_mean), size = 4) + 
		scale_x_continuous(breaks = oldest_year:current_year) +
		scale_y_continuous(breaks = 4:14, limits = c(4,14)) +
		labs(y = "Monthly mean temperature (°C)", x = "", caption = mjj_footnote) +
		facet_wrap(~month_name) + 
		ggtitle("Riwaka - May, June & July average temperature") +
		theme_bw()

ggsave(here("output/Riwaka - monthly average temperature.png"), width = 12, height = 8)
```

### May + June temperature

```{r may_june_temp}

mj_summary <- 
	daily_met_data %>% 
		filter(StationID %in% c("TPK", "RIR", "KER") & Month %in% c(5, 6) & Year >= oldest_year) %>% 
		group_by(StationID, Year) %>% 
		summarise(mj_mean = mean(c(TemperatureMin, TemperatureMax), na.rm = TRUE))

mj_summary %>% 
	mutate(StationID = factor(StationID, levels = c("KER", "TPK", "RIR"))) %>% 
	ggplot() +
		geom_point(aes(Year, mj_mean), size = 3) +
		labs(x = "Year", y = "Mean temperature - May + June  (°C)") +
		scale_y_continuous(breaks = seq(8, 16, by = 0.5)) +
		scale_x_continuous(breaks = oldest_year:current_year) +
		facet_wrap(~StationID) +
		theme_bw()

ggsave(here("output/May + June average temperature.png"), width = 12, height = 6)

```

```{r monthly_chill}

# be wary of using incomplete months in summary
# possibly filter out based on number of data points prior?
# or could just have 3 different sets for completed months
# nicer to just filter using the current date - more dynamic and works because the by site dataset only has months 5-9 (May - September)
by_site %>% 
	filter(StationID == "KER" & Year >= oldest_year & Month < month(today())) %>% 
	group_by(Year, Month) %>% 
	summarise(total_monthly_chill = last(ChillingHoursCumulative)) %>% 
	group_by(Month) %>% 
	summarise(total_chill = total_monthly_chill,
			  mean_chill = mean(total_monthly_chill[Year != current_year]), 
			  Year = Year) %>%
	ggplot() +
		geom_hline(aes(yintercept = mean_chill), alpha = 0.6, colour = "darkgrey", linetype = 2) +
		ggtitle("Kerikeri total monthly chill") +
		geom_bar(aes(Year, total_chill), stat = "identity") +
		scale_y_continuous(breaks = seq(0, 300, by = 25), limits = c(0, 300)) +
		scale_x_continuous(breaks = 2012:2022) +
		facet_wrap(~Month, labeller = labeller(Month = c("5" = "May", "6" = "June", "7" = "July"))) +
		labs(x = "", y = "Cumulative chill hours (<7°C)", caption = "dotted line shows historical monthly average") +
		theme_bw()

ggsave(here(paste0("output/Kerikeri - total monthly chill ", current_year, ".png")), width = 12, height = 8)

by_site %>% 
	filter(StationID == "TPK" & Year >= oldest_year & Year != 2017 & Month < month(today())) %>% 
	group_by(Year, Month) %>% 
	summarise(total_monthly_chill = last(ChillingHoursCumulative)) %>% 
	group_by(Month) %>% 
	summarise(total_chill = total_monthly_chill,
			  mean_chill = mean(total_monthly_chill[Year != current_year]), 
			  Year = Year) %>%
	ggplot() +
		geom_hline(aes(yintercept = mean_chill), alpha = 0.6, colour = "darkgrey", linetype = 2) +
		ggtitle("Te Puke total monthly chill") +
		geom_bar(aes(Year, total_chill), stat = "identity") +
		scale_y_continuous(breaks = seq(0, 700, by = 25), limits = c(0, 700)) +
		scale_x_continuous(breaks = 2012:2022) +
		facet_wrap(~Month, labeller = labeller(Month = c("5" = "May", "6" = "June", "7" = "July"))) +
		labs(x = "", y = "Cumulative chill hours (<7°C)", caption = "dotted line shows historical monthly average\n 2017 excluded due to sensor error") +
		theme_bw()

ggsave(here(paste0("output/Te Puke - total monthly chill ", current_year, ".png")), width = 12, height = 8)

by_site %>% 
	filter(StationID == "RIR" & Year >= oldest_year & Month < month(today())) %>% 
	group_by(Year, Month) %>% 
	summarise(total_monthly_chill = last(ChillingHoursCumulative)) %>% 
	group_by(Month) %>% 
	summarise(total_chill = total_monthly_chill,
			  mean_chill = mean(total_monthly_chill[Year != current_year]), 
			  Year = Year) %>%
	ggplot() +
		geom_hline(aes(yintercept = mean_chill), alpha = 0.6, colour = "darkgrey", linetype = 2) +
		ggtitle("Riwaka total monthly chill") +
		geom_bar(aes(Year, total_chill), stat = "identity") +
		scale_y_continuous(breaks = seq(0, 1200, by = 50), limits = c(0, 1200)) +
		scale_x_continuous(breaks = 2012:2022) +
		facet_wrap(~Month, labeller = labeller(Month = c("5" = "May", "6" = "June", "7" = "July"))) +
		labs(x = "", y = "Cumulative chill hours (<7°C)", caption = "dotted line shows historical monthly average") +
		theme_bw()

ggsave(here(paste0("output/Riwaka - total monthly chill ", current_year, ".png")), width = 12, height = 8)


```

```{r chilling_2018, eval=FALSE}

doy_ticks <- by_site%>%
				filter(StationID == "TPK" & (Month > 4 & Month < 10) & (Year >= 2008 & Year < 2019)) %$%
				pretty(x = DayOfYear, n = 7)

# labels for x axis ticks
month_ticks <- format(as.Date(doy_ticks, origin), "%b-%d")

by_site %>% 
	filter(StationID == "TPK" & (Month > 4 & Month < 10) & (!Year == 2017 & (Year >= 2008 & Year < 2019))) %>%
		ggplot() +
			geom_line(aes(DayOfYear, ChillingHoursCumulative, colour = factor(Year), size = factor(Year))) + 
			scale_size_manual(values = c(rep(0.5, 9), 1)) + 
			scale_color_manual(values = c("red", "blue", "gold", "darkcyan", "orange", "purple",
										  "forestgreen", "darkturquoise", "green",  "black")) + 
			ggtitle("Cumulative chilling hours - Te Puke 2018") +
			ylim(0,2000) + 
			scale_x_continuous(breaks = doy_ticks, labels = month_ticks) + 
			theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
			labs(x = "Date", y = "Cumulative hours (<7°C)", colour = "Year", caption = "2017 is excluded due to sensor error") + 
			guides(size = "none") + 
			theme_bw()

ggsave("../output/Winter chilling - Te Puke 2018.png", width = 12, height = 8)

by_site %>% 
	filter(StationID == "KER" & (Month > 4 & Month < 10) & (Year >= 2008 & Year < 2019)) %>%
		ggplot() +
			geom_line(aes(DayOfYear, ChillingHoursCumulative, colour = factor(Year), size = factor(Year))) + 
			scale_size_manual(values = c(rep(0.5, 10), 1)) + 
			scale_color_manual(values = c("red", "blue", "gold","darkcyan", "orange", "purple",
										  "forestgreen", "darkturquoise", "green", "cornflowerblue", "black")) + 
			ggtitle("Cumulative chilling hours - Kerikeri 2018") +
			ylim(0,1500) + 
			scale_x_continuous(breaks = doy_ticks, labels = month_ticks) + 
			theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
			labs(x = "Date", y = "Cumulative hours (<7°C)", colour = "Year") + 
			guides(size = "none") + 
			theme_bw()

ggsave("Winter chilling - Kerikeri 2019.png", width = 12, height = 8)


```

```{r budup_dates, eval=FALSE}

# G11

early_g11 <- yday(ymd("2019/07/22"))
mid_g11 <- yday(ymd("2019/08/01"))
late_g11 <- yday(ymd("2019/08/07"))
vLate_g11 <- yday(ymd("2019/09/16"))

g11 <- data.frame(doy = c(early_g11, mid_g11, late_g11, vLate_g11))

# R19

early_r19 <- yday(ymd("2019/08/03"))
mid_r19 <- yday(ymd("2019/08/15"))
late_r19 <- yday(ymd("2019/08/21"))
vLate_r19 <- yday(ymd("2019/08/29"))

r19 <- data.frame(doy = c(early_r19, mid_r19, late_r19, vLate_r19))


by_site %>% 
	filter(StationID == "TPK" & Year == 2019 & DayOfYear %in% c(g11$doy, r19$doy)) %>%
	group_by(DayOfYear) %>%
	summarise(temp_max = max(TemperatureMean),
			  temp_min = min(TemperatureMean),
			  rainfall = sum(RainTotal)) %>%
	mutate(date = as.Date(DayOfYear, origin = "2018/12/31"))
	

```

```{r hc-alt-2020, eval=FALSE}

doy_ticks <- 
	by_site%>%
	filter(StationID == "TPK" & (Month > 4 & Month < 10)) %$%
	pretty(x = DayOfYear, n = 7)

# labels for x axis ticks
month_ticks <- format(as.Date(doy_ticks, origin), "%b-%d")

tpk_2020_graph <- 
	by_site %>% 
	filter(StationID == "TPK" & (Month > 4 & Month < 10) & Year > 2010 & !Year == 2017 & Year < 2021) %>%
		ggplot() +
			geom_line(aes(DayOfYear, ChillingHoursCumulative, colour = factor(Year), size = factor(Year))) + 
			scale_size_manual(values = c(rep(0.5, 8), 1)) + 
			scale_color_manual(values = c("red", "blue", "gold","darkcyan", "brown", "purple",
										  "forestgreen", "darkturquoise",  "black")) + 
			ggtitle("Cumulative chilling hours - Te Puke 2020") +
			scale_x_continuous(breaks = doy_ticks, labels = month_ticks) + 
			scale_y_continuous(breaks = seq(0, 1000, 100), limits = c(0,1000),
							   expand = c(0,0)) +
			labs(x = "Date", y = "Cumulative hours (<7°C)", colour = "Year", caption = "2017 is excluded due to sensor error") + 
			guides(size = "none") + 
			publish_theme()


ggsave(here("output/Winter chilling (HC-alt) - Te Puke 2020.png"), tpk_2020_graph, width = 12, height = 8)

ker_2020_graph <- 
	by_site %>% 
	filter(StationID == "KER" & (Month > 4 & Month < 10) & Year > 2010 & Year < 2021) %>%
		ggplot() +
			geom_line(aes(DayOfYear, ChillingHoursCumulative, colour = factor(Year), size = factor(Year))) + 
			scale_size_manual(values = c(rep(0.5, 9), 1)) + 
			scale_color_manual(values = c("red", "blue", "gold","darkcyan", "brown", "purple",
										  "forestgreen", "darkturquoise", "hotpink",  "black")) + 
			ggtitle("Cumulative chilling hours - Kerikeri 2020") +
			scale_x_continuous(breaks = doy_ticks, labels = month_ticks) + 
			scale_y_continuous(breaks = seq(0, 1000, 100), limits = c(0,1000),
							   expand = c(0,0)) +
			labs(x = "Date", y = "Cumulative hours (<7°C)", colour = "Year") + 
			guides(size = "none") + 
			publish_theme()


ggsave(here("output/Winter chilling (HC-alt) - Kerikeri 2020.png"), ker_2020_graph, width = 12, height = 8)

```

```{r api_scratch, eval=FALSE}
# librarys needed for api call
library(httr)
library(jsonlite)


api_key <- "hVmYq3t6w9z$C&F)J@McQfTjWnZr4u7x"
api_base_url <- "https://api.metwatch.nz/"
api_hourly_data_url <- "api/legacy/weather/hourly?station="

# BP1 = Tauranga Aero
station_id <- "BP1"

start_date <- "2022-05-01T08:00:00"
end_date <- "2022-06-19T08:00:00"

# get station & date range

response <- GET(paste0(api_base_url, api_hourly_data_url, station_id, "&start=", start_date, "&stop=", end_date),
				config = add_headers("X-Api-Key" = api_key, "Accept" = c("*/*", "application/json")))

parsed_response <- content(response, "text")
json_response <- parse_json(parsed_response, TRUE)

hourly_data <- 
	data.frame(StationID = station_id,
			   StopDate = as.POSIXct(json_response$STOPSTAMP, origin = ymd("1970-01-01"), tz = "NZ"),
			   TemperatureMean = json_response$TDDATA)


# now do chill things
hourly_data %>% 
	mutate(cumulative_chill = cumsum(ifelse(TemperatureMean< 7, 1, 0))) %>% 
	ggplot() +
		geom_line(aes(StopDate, cumulative_chill, colour = "Aero")) +
		geom_line(aes(StopDate, cumulative_chill, colour = "TPK"), 
				  data = met_data %>% 
				  			filter(StationID == "TPK" & StopDate > ymd("2022-05-01") & StopDate < ymd("2022-06-20")) %>% 
				  			mutate(cumulative_chill = cumsum(ifelse(TemperatureMean< 7, 1, 0)))) +
		scale_x_datetime(breaks = pretty_breaks(10)) +
		theme_bw()
```

```{r scratch, eval=FALSE}

# Annette found 7.2C is the correct cutoff of chilling to occur
# how does this stack up against 7C for Kerikeri

by_site %>% 
	filter(StationID == "KER" & Year == 2021) %>% 
	mutate(alt_hours = case_when(TemperatureMean <= 7.2 ~ 1, 
								 TemperatureMean > 7.2 ~ 0, 
								 is.na(TemperatureMean) ~ 0),
		   alt_cumulative = cumsum(alt_hours)) %>% 
	ggplot() +
		geom_line(aes(DayOfYear, ChillingHoursCumulative, colour = "7C")) +
		geom_line(aes(DayOfYear, alt_cumulative, colour = "7.2C")) +
		scale_colour_manual(values = c("7C" = "black", "7.2C" = "skyblue")) +
		scale_y_continuous(breaks = pretty_breaks(10), limits = c(0, 600)) +
		scale_x_continuous(breaks = pretty_breaks(20), limits = c(121, 275)) +
		theme_bw()


# How about Te Puke
by_site %>% 
	filter(StationID == "TPK" & Year == 2021) %>% 
	mutate(alt_hours = case_when(TemperatureMean <= 7.2 ~ 1, 
								 TemperatureMean > 7.2 ~ 0, 
								 is.na(TemperatureMean) ~ 0),
		   alt_cumulative = cumsum(alt_hours)) %>% 
	ggplot() +
		geom_line(aes(DayOfYear, ChillingHoursCumulative, colour = "7C")) +
		geom_line(aes(DayOfYear, alt_cumulative, colour = "7.2C")) +
		scale_colour_manual(values = c("7C" = "black", "7.2C" = "skyblue")) +
		scale_y_continuous(breaks = pretty_breaks(10), limits = c(0, 600)) +
		scale_x_continuous(breaks = pretty_breaks(20), limits = c(121, 275)) +
		theme_bw()


# Look for any missing values at the three sites for the current year
by_site %>% 
	filter(Year == current_year & is.na(TemperatureMean) & StationID %in% c("KER", "TPK", "RIW")) %>% 
	kable() %>% 
	kable_styling("striped")

# Only TPK has any (today = 2021-08-31)
na_data_tpk <- 
	by_site %>% 
	filter(Year == current_year & is.na(TemperatureMean) & StationID == "TPK")

# find if there is matches in the raw file
# huh there isnt, wierd.
tpk_raw <- 
	read_csv(here("input/TPK.dat")) %>% 
	rename(ArrayID = 1, Year = 3, doy = 4, hm = 5, airtemp = 6) %>% 
	mutate(StopDate = as.Date(doy, origin = ymd(paste(Year - 1, "12-31", sep = "-"))),
		   StopDate = as_datetime(StopDate + hm/2400)) %>% 
	filter(ArrayID == 20 & Year == 2021)


# data table for TPK and KER with below 7C and Richardson units by year
by_site %>%
  filter(StationID %in% c("KER", "TPK") & (Month > 4 & Month < 10) & !is.na(TemperatureMean)) %>%
  group_by(StationID, Year) %>%
  mutate(richardsonUnit = richardsonChillTable$value[findInterval(TemperatureMean, richardsonChillTable$RangeMax[-7]) + 1],
    	 richardsonChillingHours = cumsum(richardsonUnit)) %>%
  slice(n()) %>%
  select(StationID, Year, ChillingHoursCumulative, richardsonChillingHours) %>%
  filter(Year == 2021) %>%
  write_csv(here("output/Chilling hours table tpk ker.csv"))


# old monthly temps but using hourly data rather than daily
met_data %>%
    filter(StationID == "TPK" & !is.na(TemperatureMean)) %>%
    group_by(Year, Month) %>%
    summarise(avg_temp = mean(TemperatureMean, na.rm = TRUE)) %>%
    arrange(Month) %>%
    ggplot() +
        geom_point(aes(Year, avg_temp, colour = avg_temp)) +
		scale_colour_gradient2(low = "blue", mid = "pink", high = "red", midpoint = 14) +
		geom_smooth(aes(Year, avg_temp), method = "lm") +
        facet_wrap(~Month, 
        		   nrow = 1,
        		   scales = "free_x", 
        		   labeller = labeller(Month = c("1" = "January",
        		   								 "2" = "February",
        		   								 "3"  = "March", 
        		   								 "4" = "April",
        		   								 "5" = "May",
        										 "6" = "June", 
        										 "7" = "July", 
        										 "8" = "August", 
        										 "9" = "September", 
        										 "10" = "October", 
        										 "11" = "November", 
        										 "12" = "December"))) + 
		
		theme_bw() +
		theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
```
